name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: payouts_test
          POSTGRES_USER: payouts
          POSTGRES_PASSWORD: payouts
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U payouts"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    # env:
    #   DATABASE_URL: postgres://payouts:payouts@localhost:5432/payouts_test
    #   DJANGO_SETTINGS_MODULE: payout_service.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0
          pip install -r ./payouts_project/requirements.txt

      - name: Test with flake8 and django tests
        env:
          POSTGRES_USER: payouts
          POSTGRES_PASSWORD: payouts
          POSTGRES_DB: payouts_test
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m flake8 payouts_project/
          cd payouts_project/
          python manage.py test
